# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CiI2BLY199G9kPI5hnTQGZ8LNXNGQgT5
"""

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
def hitung_faktorial(n):
    if n < 0:
        return "Faktorial tidak dapat dihitung untuk bilangan negatif."
    elif n == 0 or n == 1:
        return 1
    else:
        hasil = 1
        for i in range(2, n + 1):
            hasil *= i
        return hasil

# Input dari pengguna
bilangan = int(input("nilai: "))

# Memanggil fungsi hitung_faktorial dan mencetak hasilnya
print(f"Faktorial dari {bilangan} adalah {hitung_faktorial(bilangan)}")

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
def hitung_vokal_dan_konsonan(kalimat):
    # Inisialisasi jumlah vokal dan konsonan
    jumlah_vokal = 0
    jumlah_konsonan = 0

    # Konversi kalimat menjadi huruf kecil untuk memudahkan penghitungan
    kalimat = kalimat.lower()

    # Loop melalui setiap karakter dalam kalimat
    for karakter in kalimat:
        # Periksa apakah karakter merupakan huruf
        if karakter.isalpha():
            # Periksa apakah huruf tersebut merupakan vokal atau konsonan
            if karakter in 'aeiou':
                jumlah_vokal += 1
            else:
                jumlah_konsonan += 1

    # Tampilkan hasil
    print(f"Jumlah huruf vokal: {jumlah_vokal}")
    print(f"Jumlah huruf konsonan: {jumlah_konsonan}")

# Contoh penggunaan
kalimat_input = input("Masukkan kalimat: ")
hitung_vokal_dan_konsonan(kalimat_input)

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
def kubik_angka(angka):
    # Mengembalikan nilai kubik dari suatu angka
    return angka ** 3

def cek_habis_dibagi_tiga(angka):
    # Mengecek apakah angka habis dibagi 3
    if angka % 3 == 0:
        # Jika habis dibagi 3, jalankan fungsi pertama
        hasil_kubik = kubik_angka(angka)
        return hasil_kubik
    else:
        # Jika tidak habis dibagi 3, kembalikan tulisan "False"
        return False

# Contoh penggunaan
angka_input = int(input("Masukkan angka: "))

hasil_cek = cek_habis_dibagi_tiga(angka_input)

if hasil_cek is not False:
    print(f"Hasil kubik dari {angka_input} adalah: {hasil_cek}")
else:
    print(f"{angka_input} false")